# Generated by Django 6.0.2 on 2026-02-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
