# Generated by Django 6.0.2 on 2026-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_admin_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='admin_reply',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
